services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /doctors
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html